name: Quality Control

on:
  push:
    branches: ['*']

  pull_request:
    branches: ['*']

jobs:
  quality-control:
    name: Quality Control
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      # Run static analyze
      - name: Run static analyze
        run: ./gradlew :gridpad:detekt

      # Run unit testing
      - name: Run unit testing
        run: ./gradlew :gridpad:test